# Generated by scripts/release-manifests.sh — don't edit by hand.
class Malveon < Formula
  desc "Checks whether an AI coding agent's claimed-done work actually matches your plan, by reading the real code"
  homepage "https://github.com/LadsonDavid/Malveon"
  version "0.3.1"
  license :cannot_represent # Malveon Beta License, see LICENSE

  on_macos do
    on_arm do
      url "https://github.com/LadsonDavid/Malveon/releases/download/v0.3.1/malveon-darwin-arm64"
      sha256 "c453d6912b0ac568e5936c52c23970e392f94a082fd6098036af06502a559402"
    end
    on_intel do
      url "https://github.com/LadsonDavid/Malveon/releases/download/v0.3.1/malveon-darwin-amd64"
      sha256 "e30635c9ebff942dce694aeab648562c1dcdbed56d0a98eb957d38fdd2e1d28a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/LadsonDavid/Malveon/releases/download/v0.3.1/malveon-linux-amd64"
      sha256 "e15e1dd14060030d099667c598035e2112d3349778a74ad79578a4a99865f90e"
    end
  end

  def install
    bin.install Dir["malveon-*"].first => "malveon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/malveon version")
  end
end
