# Generated by scripts/release-manifests.sh — don't edit by hand.
class Malveon < Formula
  desc "Checks whether an AI coding agent's claimed-done work actually matches your plan, by reading the real code"
  homepage "https://github.com/LadsonDavid/Malveon"
  version "0.3.4"
  license :cannot_represent # Malveon Beta License, see LICENSE

  on_macos do
    on_arm do
      url "https://github.com/LadsonDavid/Malveon/releases/download/v0.3.4/malveon-darwin-arm64"
      sha256 "b2010985a9525d1e9384568aaa88d6d373b018193cfe4ce3843e93058ba04b38"
    end
    on_intel do
      url "https://github.com/LadsonDavid/Malveon/releases/download/v0.3.4/malveon-darwin-amd64"
      sha256 "561883b144f773ed90fcc99d30f9240dbfed85624b5418853a9419f909ad1773"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/LadsonDavid/Malveon/releases/download/v0.3.4/malveon-linux-amd64"
      sha256 "6ca98ec6f302165ccf16fd4ecfa490ba48302443e56a5f4a980df08966fdeba7"
    end
  end

  def install
    bin.install Dir["malveon-*"].first => "malveon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/malveon version")
  end
end
