# Generated by scripts/release-manifests.sh — don't edit by hand.
class Malveon < Formula
  desc "Checks whether an AI coding agent's claimed-done work actually matches your plan, by reading the real code"
  homepage "https://github.com/LadsonDavid/Malveon"
  version "0.3.0"
  license :cannot_represent # Malveon Beta License, see LICENSE

  on_macos do
    on_arm do
      url "https://github.com/LadsonDavid/Malveon/releases/download/v0.3.0/malveon-darwin-arm64"
      sha256 "84c794b0f7fe716aaad3ab159b3ccf1c5cd028793b43fd1a4945374de5e7619a"
    end
    on_intel do
      url "https://github.com/LadsonDavid/Malveon/releases/download/v0.3.0/malveon-darwin-amd64"
      sha256 "840ae6c2415c767755f47f767f33e52dc53c987f1c10d0534302f3b1b4d834fc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/LadsonDavid/Malveon/releases/download/v0.3.0/malveon-linux-amd64"
      sha256 "eed3858ea5e0dad47af6271553e7978b66ccc66735b86f7ae61a6bf2454029c9"
    end
  end

  def install
    bin.install Dir["malveon-*"].first => "malveon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/malveon version")
  end
end
